This is a step by step build out for OpenShift 4.6 with FIPS enabled + Service Mesh

*NOTE: This build is specifically on VMWare ESXi 6.7*

I will not go through the build of the bastion host - you can find this in the OpenShift docs here: 

https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html-single/installing/index


From the cli on the bastion host create an install-config with the following command:

---

`#./openshift-install create install-config --dir=_<operating_dir>_ --log-level=debug` +

---

The _<operating_dir>_ is used for all the config files for that specific cluster.

Next you will edit the install-config.yaml file located in your _<operating_dir>_ - below is an example of one wtih FIPS enabled:

---
.install-config.yaml

[source,yaml]
apiVersion: v1
baseDomain: test.gusszz.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: ocp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 10.0.0.32
    cluster: cluster
    datacenter: Datacenter
    defaultDatastore: Datastore_2
    ingressVIP: 10.0.0.33
    network: VM Network
    password: Redhat1!Redhat
    username: administrator@vsphere.local
    vCenter: 10.0.0.52
publish: External
fips: true
pullSecret: ''
sshKey: ''

---

**Please note the 'fips: true'** +
This will tell the cluster to enable fips on all the hosts. 
This can be verified once the cluster is up and running by doing the following:

---
----
# oc get nodes   
# oc debug node/_<name_of_a_node>_  
$ fipscheck  
----

- You should see the command return "fips is on"

---

Once the cluster comes up, login & verify that all status are [green]#green#.

*The following steps are for installing, configuring and testing the Service Mesh Control Plane*

1. Go to 'Operator Hub' and serch for the following list & install them with the defaults selected
  - Elasticserch Operator - provided by Red Hat
  - Red Hat OpenShift Jaeger - provided by Red Hat
  - Red Hat OpenShift Service Mesh - provided by Red Hat
2. Verify that the install(s) completed successfully
3. Use the httpbin.tar file and copy to your bastion host
4. Un-tar the file - there should be the following files:
  - cmd
  - httpbin.yaml
  - smcp.yaml
  - smm.yaml
5. Run the cmd command  
----
# sh cmd
----
  - This will install and configure the Service Mesh Control Plane for you and install an application that can be tested to verify that the Service Mesh is functioning properly with FIPS enabled on the OCP cluster.  

6. Issue the following command to verify SMCP is working properly:  
----
  curl -v http://$(oc get route -n istio-system istio-ingressgateway -o jsonpath='{.spec..host}')/headers
----
  - This command should give a '200 ok' status if working properly
